### ISSUE TITLE
BaseFilePathHandler has different working logic in Python 3.7 and Python 3.8, causing error reading files.

### ISSUE THREAD

**Issue by NotChristianGarcia** [p1c2u/jsonschema-spec#14]
Seems like the difference between `typing` and `typing_extensions` is causing a problem later on in Python 3.7 vs. Python 3.8. https://github.com/p1c2u/jsonschema-spec/blob/da5e04c7b3481e62555d9c3820496030b188d1de/jsonschema_spec/handlers/protocols.py#L5-L10

Here's a quick code snippet to test, for some reason the fh object in Python 3.8 is an instance of SupportsRead, and Python 3.7 it is not.

```
from urllib.request import urlopen
from jsonschema_spec.handlers.protocols import SupportsRead

with urlopen('file:///testing.yml') as fh:         # ref#1
	if isinstance(fh, SupportsRead):               # ref#2
		print("supports read!")
		
# simplifies to the following for testing, above is just more readable
with urlopen('file:///testing.yml') as fh: isinstance(fh, SupportsRead)
```

This causes code in `file.py` to continue to `parsed_url = urlparse(uri)`. Which will give the following error: `AttributeError: '_io.BufferedReader' object has no attribute 'decode'`. This in turn causes `openapi-spec` to break when running `Spec.from_file_path` in Python 3.7 when it works in Python 3.8.

I need to go eat, but you might understand what's happening more. And I imagine you'll want it fixed as it breaks < Python 3.7 versions. I'll figure out why the diff occurs later.

## references

ref#1: https://github.com/p1c2u/jsonschema-spec/blob/da5e04c7b3481e62555d9c3820496030b188d1de/jsonschema_spec/handlers/urllib.py#L17-L18
ref#2: https://github.com/p1c2u/jsonschema-spec/blob/da5e04c7b3481e62555d9c3820496030b188d1de/jsonschema_spec/handlers/file.py#L38-L39

**Comment by NotChristianGarcia** [comment]
I've looked a tad more. I believe that in <= 3.7 the `isinstance(fh, protocolClass)` isn't searching the fh object as deeply as in 3.8+.

For instance, I created `runtime_checkable` classes which check for base object methods (`dir(fh)`) such as `geturl`, `info`, `getcode`, `close`, etc. That works correctly, but I can't check for methods from inherited objects. In this case the read() method in BufferedReader comes from the io.RawIOBase, io.BufferedIOBase, or io.IOBase.

It's your code, so feel free to do what you want, but ditching `runtime_checkable` in favor of something like the following would work as well. `runtime_checkable` doesn't actually confirm methods follow the type hints, so there wouldn't be much difference.

```
def is_readable(obj: object) -> bool:
    return hasattr(obj, 'read') and callable(obj.read)
is_readable(fh)```

**Comment by p1c2u** [comment]
I found the issue. It caused by new [4.6 version of typing-extensions](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-460-may-22-2023) used by jsonschema-spec to validate protocol.

> isinstance() checks against runtime-checkable protocols now use inspect.getattr_static() rather than hasattr() to lookup whether attributes exist (backporting https://github.com/python/cpython/pull/103034). This means that descriptors and __getattr__ methods are no longer unexpectedly evaluated during isinstance() checks against runtime-checkable protocols. However, it may also mean that some objects which used to be considered instances of a runtime-checkable protocol on older versions of typing_extensions may no longer be considered instances of that protocol using the new release, and vice versa. Most users are unlikely to be affected by this change. Patch by Alex Waygood.

Temporary workaround will be downgrading typing-extensions to version below 4.6:

> pip install "typing-extensions<4.6"

**Comment by mgorny** [comment]
> Versions 4.6.x won't be supported because of the issue #14

Does this mean that this package will forever prevent people from installing newer typing-extensions, eventually making it impossible to use it along with other packages that require new typing-extensions (because they need features from new Python versions)?

**Comment by p1c2u** [comment]
> > Versions 4.6.x won't be supported because of the issue #14
> 
> 
> 
> Does this mean that this package will forever prevent people from installing newer typing-extensions, eventually making it impossible to use it along with other packages that require new typing-extensions (because they need features from new Python versions)?

Only for Python 3.7 which ends it's life in 2 weeks. Newer versions won't need typing-extensions (at least for protocol checking).

**Comment by mgorny** [comment]
> Only for Python 3.7 which ends it's life in 2 weeks. Newer versions won't need typing-extensions (at least for protocol checking).

Is there a reason why the dependency doesn't come with `python = "<3.8"` specifier then?

**Comment by p1c2u** [comment]
Fair point.
